[Service]
ExecStart=
ExecStart=/usr/local/libexec/jarvis-command-apply-nftables start
ExecReload=
ExecReload=/usr/local/libexec/jarvis-command-apply-nftables reload
ExecStop=
ExecStop=/usr/local/libexec/jarvis-command-apply-nftables stop
